### ISSUE TITLE
Why i can't play in column 5

### ISSUE THREAD

**Issue by alrifay** [JonathanGin52/JonathanGin52#244]
The github actions threw an error when i was about to win 😞.
```

 Check failure on line 1 in .github

@github-actions
github-actions
/ move

.github#L1
Process completed with exit code 1.
```

**Comment by JonathanGin52** [comment]
I fixed the issue, you should be good to go now :)

**Comment by JonathanGin52** [comment]
Please try again now 😅

**Comment by alrifay** [comment]
I won 🎉🤣

**Comment by JonathanGin52** [comment]
Haha thanks for helping me discover an issue. Made a few big code changes this afternoon and some stuff slipped by
